wedding invitation lading page
kngcl/wedding pull request #1
Opened 2022-11-02 15:40 UTC by kngcl

The landing page has five sections headers, home, wedding, RSVP, jane-john and footer sections. The landing page actually serves as an invitation to people.

2022-11-07 09:44 UTC, nganifaith requested changes

2022-11-07 09:44 UTC, nganifaith commented on Readme.md
> +
missing a brief project description.

2022-11-07 09:44 UTC, nganifaith commented on Readme.md
> +- $ `git checkout feature`
which feature branch?

- [ ] indicate feature branch that contains all your work

2022-11-07 09:44 UTC, nganifaith commented on Readme.md
> +- run `npm install`
project doesn't require npm to run.

- [ ] explain how to run project

2022-11-07 09:44 UTC, nganifaith commented on Readme.md
> +
You are not working on any test. section isn't required.

- [ ] remove test section

2022-11-07 09:44 UTC, nganifaith commented on Readme.md
> +- run `npm install`
Explain how to open project on browser

2022-11-07 09:44 UTC, nganifaith commented on Readme.md
> +
prerequisite section should have include:


- [ ]  knowledge of HTML and CSS and 
- [ ]  browser installed in order to run project

2022-11-07 09:44 UTC, nganifaith commented on index.html
> +                <p><a href="#jane-john">Jane and John</a></p>
Expected nav bar to be in a header tag

2022-11-07 09:47 UTC, nganifaith commented
Implement changes and submit for another review

2022-11-07 10:24 UTC, kngcl commented on index.html
> +                <p><a href="#jane-john">Jane and John</a></p>
Done

2022-11-07 10:24 UTC, kngcl commented on Readme.md
> +- run `npm install`
Done

2022-11-07 10:43 UTC, nganifaith requested changes
@kngcl Great progress working on the review. You are on step away from having it approved.
Implement the changes and send me a message on slack

2022-11-07 10:43 UTC, nganifaith commented on Readme.md
> +- $ git clone `https://github.com/kngcl/wedding/tree/feature/header`
- [ ] link to the repository

2022-11-07 10:43 UTC, nganifaith commented on Readme.md
> +
what are the prerequisites to run or have the project install on your machine

2022-11-07 10:43 UTC, nganifaith commented on Readme.md
> +this project is all about online invitation.
Give a description that can make someone want to visit the site or have it on their local machine

2022-11-08 10:08 UTC, nganifaith approved these changes
Congratulations 🍻🥁🥁🎉🎉🎉🎊🎊🎊🎊🎊🎉🎉🎊🎉🎊🎉🎉🎊🎉🎉🎉@kngcl. You can go ahead and merge your work. 

**Optional**
  

- [ ] footer section doesn't look like the original page

2022-11-15 09:29 UTC, merged